"""fresh schema

Revision ID: f87a239a4794
Revises: 
Create Date: 2026-04-10 11:57:00.931981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f87a239a4794'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('brand_name', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('current_ticket_number', sa.Integer(), nullable=False),
    sa.Column('ticket_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('lookup_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('lookup_type', sa.String(length=30), nullable=False),
    sa.Column('value', sa.String(length=200), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'lookup_type', 'value', name='uq_lookup_tenant_type_value')
    )
    with op.batch_alter_table('lookup_values', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lookup_values_lookup_type'), ['lookup_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_lookup_values_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active_user', sa.Boolean(), nullable=False),
    sa.Column('is_super_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('before_value', sa.JSON(), nullable=True),
    sa.Column('after_value', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index('ix_audit_entity', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_audit_tenant_date', ['tenant_id', 'created_at'], unique=False)

    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_number', sa.Integer(), nullable=False),
    sa.Column('ticket_display', sa.String(length=4), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('raw_input', sa.Text(), nullable=False),
    sa.Column('direction', sa.String(length=1), nullable=False),
    sa.Column('total_quantity', sa.Integer(), nullable=False),
    sa.Column('filled_quantity', sa.Integer(), nullable=False),
    sa.Column('package_premium', sa.Float(), nullable=True),
    sa.Column('strategy', sa.String(length=20), nullable=True),
    sa.Column('is_generic', sa.Boolean(), nullable=False),
    sa.Column('house', sa.String(length=50), nullable=True),
    sa.Column('account', sa.String(length=50), nullable=True),
    sa.Column('bk_broker', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('time_in', sa.DateTime(timezone=True), nullable=False),
    sa.Column('time_out', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modification_timestamps', sa.JSON(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'trade_date', 'ticket_number', name='uq_tenant_date_ticket')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_trade_date'), ['trade_date'], unique=False)

    op.create_table('fills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('fill_quantity', sa.Integer(), nullable=False),
    sa.Column('fill_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('allocation_status', sa.String(length=30), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fills_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fills_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('order_legs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('leg_index', sa.Integer(), nullable=False),
    sa.Column('side', sa.String(length=1), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('market', sa.String(length=10), nullable=False),
    sa.Column('contract_type', sa.String(length=10), nullable=False),
    sa.Column('expiry', sa.String(length=10), nullable=False),
    sa.Column('strike', sa.Float(), nullable=True),
    sa.Column('option_type', sa.String(length=1), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('mo_card_code', sa.String(length=10), nullable=True),
    sa.Column('package_premium', sa.Float(), nullable=True),
    sa.Column('suppress_premium', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_legs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_legs_order_id'), ['order_id'], unique=False)

    op.create_table('print_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=20), nullable=False),
    sa.Column('printed_by_id', sa.Integer(), nullable=False),
    sa.Column('data_snapshot', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['printed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('print_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_print_events_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_print_events_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('fill_counterparties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fill_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('broker', sa.String(length=50), nullable=False),
    sa.Column('symbol', sa.String(length=100), nullable=False),
    sa.Column('bracket', sa.String(length=10), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['fill_id'], ['fills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fill_counterparties', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fill_counterparties_fill_id'), ['fill_id'], unique=False)

    op.create_table('fill_leg_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fill_id', sa.Integer(), nullable=False),
    sa.Column('leg_index', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['fill_id'], ['fills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fill_id', 'leg_index', name='uq_fill_leg_price')
    )
    with op.batch_alter_table('fill_leg_prices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fill_leg_prices_fill_id'), ['fill_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fill_leg_prices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fill_leg_prices_fill_id'))

    op.drop_table('fill_leg_prices')
    with op.batch_alter_table('fill_counterparties', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fill_counterparties_fill_id'))

    op.drop_table('fill_counterparties')
    with op.batch_alter_table('print_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_print_events_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_print_events_order_id'))

    op.drop_table('print_events')
    with op.batch_alter_table('order_legs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_legs_order_id'))

    op.drop_table('order_legs')
    with op.batch_alter_table('fills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fills_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_fills_order_id'))

    op.drop_table('fills')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_trade_date'))
        batch_op.drop_index(batch_op.f('ix_orders_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_orders_status'))

    op.drop_table('orders')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_tenant_date')
        batch_op.drop_index(batch_op.f('ix_audit_log_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_log_action'))
        batch_op.drop_index('ix_audit_entity')

    op.drop_table('audit_log')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('lookup_values', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lookup_values_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_lookup_values_lookup_type'))

    op.drop_table('lookup_values')
    op.drop_table('tenants')
    # ### end Alembic commands ###
